apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
  namespace: vessel-dev
spec:
  type: NodePort
  ports:
    - ports:
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: flask-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-deployment
  namespace: vessel-dev
  labels:
    app: flask-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-test
  template:
    metadata:
      labels:
        app: flask-test
    spec:
      containers:
      - name: flask-test
        image: artifactory.pfizer.com/vessel-core-docker-dev/flask-test-rest-api-7-9-2021
        ports:
        - containerPort: 5000
